name: Build and Publish Debug APk

on:
  push:
    branches: [ internal-beta ]
  pull_request:
    branches: [ internal-beta ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release Artifact
        run: ./gradlew bundleRelease

      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        #  keyPassword: ${{ secrets.KEY_PASSWORD }}



      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.poli.prevendasomie
          releaseFiles: app/build/outputs/apk/debug/*.apk
          track: internal
          inAppUpdatePriority: 1

        
        
        
        
        
        
        


